### ISSUE TITLE
Milestones: Week 1

### ISSUE THREAD

**Issue by chris8736** [chris8736/intro_platformer#1]
Priority tasks:
- [ ] Make a input-controlled square that can move left, right, and jump well
- [ ] Design a fun first level using a simple 2D tilemap
- [ ] Import bouncy placeholder audio and sound effects

New tasks:
- [ ] Do win detection and scene transitions
- [ ] Implement side-scrolling
- [ ] Design triangle baddies
...

**Comment by chris8736** [comment]
Resources

**Input**
https://www.youtube.com/watch?v=Au8oX5pu5u4
Excellent Brackeys video connecting keyboard input to applied force.

**Tilemapping**
https://docs.unity3d.com/Manual/class-Tilemap.html
Official Unity tilemap documentation - see children for specifics
https://www.youtube.com/watch?v=ryISV_nH8qw
Corresponding Brackeys video
